# Generated by Django 5.0.4 on 2024-05-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parsercounry_remove_currency_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
                ('currency_code', models.CharField(max_length=3, verbose_name='Код валюты')),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.CharField(max_length=10, verbose_name='Код страны'),
        ),
        migrations.DeleteModel(
            name='ParserCurrency',
        ),
    ]
