# Generated by Django 5.0.4 on 2024-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_country_alter_currency_country_delete_parsercurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParserCounry',
        ),
        migrations.AddField(
            model_name='currency',
            name='change',
            field=models.CharField(default='', max_length=7, verbose_name='Изменение курса'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Код валюты'),
        ),
    ]
