# Generated by Django 5.0.4 on 2024-05-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_delete_parsercounry_currency_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency_code',
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies',
                                    to='main.country'),
        ),
    ]
